name: Package and Release TF Config
on:
  push:
    branches: [ main ]
    paths:
      - 'tf/**'
jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Zip tf folder
        run: zip -r reececonfig.zip tf
      - name: Delete old release and tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete latest --yes --cleanup-tag || true
      - name: Create fresh release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Latest Config"
          files: reececonfig.zip
          make_latest: true